#$schema: https://json.schemastore.org/github-workflow

# 工作流名称
name: Sync-Images-to-Harbor
# 工作流运行时显示名称
run-name: ${{ github.actor }} - Sync Images to Harbor.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      images_src:
        description: '源镜像（例如：nginx:1.27）'
        required: true
      images_dest:
        description: '目标镜像（例如：docker.io/nginx:1.27）'
        required: true

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        
        echo "源镜像：${{ inputs.images_src }}"
        echo "目标镜像：${{ inputs.images_dest }}"
        skopeo copy docker://${{ inputs.images_src }} docker://${{ secrets.HARBOR_REGISTRY }}/${{ inputs.images_dest }}
 
