# 工作流名称
name: Sync-Images-to-AliYuncs
# 工作流运行时显示名称
run-name: ${{ github.actor }} - Sync Images to AliYuncs.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      images:
        description: '镜像'
        required: true

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        echo "Sync Images to registry.cn-shenzhen.aliyuncs.com/nicholyx/${{ inputs.images }}"
        skopeo copy docker://${{ inputs.images }} docker://registry.cn-shenzhen.aliyuncs.com/nicholyx/${{ inputs.images }}
 
